[template]
ignore = [".git", "README.md"]

[hooks]
pre = ["arch.rhai"]

[placeholders.chip]
prompt = "Chip name?"
default = "stm32f103c8"
type = "string"

[placeholders.arch]
prompt = "Chip's architecture?"
choices = ["cortex-M0, M0+ or M1", "Cortex-M3", "Cortex-M4 or M7", "Cortex-M4F or M7F", "Cortex-M23", "Cortex-M33 or M35P", "Cortex-M33F or M35PF"]
default = "Cortex-M3"
type = "string"
