[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Make sure your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip {{ chip | upcase }}"

[build]
target = "{{ arch }}"

[env]
DEFMT_LOG = "trace"
